variables:
  # Agent VM image name
  vmImage: "ubuntu-latest"

  # .net
  dotNetVersion: "8.0.x"
  buildConfiguration: "Release"
  buildPlatform: "AnyCPU"
  buildProjects: "**/*.csproj"
  testProjects: "**/*Tests/*.csproj"
  publishProjects: "**/*Api.csproj"
  warningThreshold: 10
  coverageThreshold: 10
  disable.coverage.autogenerate: "true"

  #SonarCloud
  sonarCloudEndpoint: "SonarCloud"
  sonarCloudOrganization: "krosoft-dev"
  sonarCloudProjectKey: "krosoft-dev_Krosoft.Extensions"
  sonarCloudProjectName: "Krosoft.Extensions"
